import type { BOQItem } from '@/lib/types'

export function exportBOQToPDF(
  items: BOQItem[],
  projectName: string,
  currency: string,
  vatPct: number
) {
  const sections = groupBySection(items)
  let grandSubtotal = 0

  const fmt = (n: number) => n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })

  let tableRows = ''
  for (const [section, sectionItems] of sections) {
    if (section) {
      tableRows += `<tr class="section"><td colspan="6">${esc(section.toUpperCase())}</td></tr>`
    }
    let sectionTotal = 0
    for (const item of sectionItems) {
      const amount = item.total_amount ?? (item.quantity * (item.unit_rate ?? 0))
      sectionTotal += amount
      tableRows += `<tr>
        <td>${esc(item.code ?? '')}</td>
        <td class="desc">${esc(item.description)}</td>
        <td class="center">${esc(item.unit)}</td>
        <td class="num">${fmt(item.quantity)}</td>
        <td class="num">${fmt(item.unit_rate ?? 0)}</td>
        <td class="num">${fmt(Math.round(amount * 100) / 100)}</td>
      </tr>`
    }
    if (section) {
      tableRows += `<tr class="subtotal"><td colspan="5" class="right">${esc(section)} Subtotal</td><td class="num">${fmt(Math.round(sectionTotal * 100) / 100)}</td></tr>`
    }
    grandSubtotal += sectionTotal
  }

  const vatAmount = grandSubtotal * (vatPct / 100)
  const grandTotal = grandSubtotal + vatAmount

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>BOQ - ${esc(projectName)}</title>
<style>
  @page { size: A4 landscape; margin: 15mm; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 10px; color: #1e293b; }
  .header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 16px; padding-bottom: 12px; border-bottom: 2px solid #1e40af; }
  .header h1 { font-size: 18px; color: #1e40af; }
  .header .meta { text-align: right; font-size: 9px; color: #64748b; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #1e40af; color: white; padding: 6px 8px; text-align: left; font-weight: 600; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
  td { padding: 5px 8px; border-bottom: 1px solid #e2e8f0; font-size: 10px; }
  tr:nth-child(even) { background: #f8fafc; }
  .section td { background: #f1f5f9; font-weight: 700; font-size: 10px; color: #334155; border-bottom: 1px solid #cbd5e1; padding: 8px; }
  .subtotal td { background: #f1f5f9; font-weight: 600; border-top: 1px solid #94a3b8; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .right { text-align: right; }
  .center { text-align: center; }
  .desc { min-width: 200px; }
  .totals { margin-top: 0; }
  .totals td { padding: 6px 8px; font-size: 10px; }
  .totals .grand { background: #1e40af; color: white; font-weight: 700; font-size: 12px; }
  .footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #e2e8f0; font-size: 8px; color: #94a3b8; display: flex; justify-content: space-between; }
  @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
</style>
</head><body>
<div class="header">
  <div><h1>Bill of Quantities</h1><div style="font-size:12px;color:#475569;margin-top:2px">${esc(projectName)}</div></div>
  <div class="meta">Currency: ${esc(currency)}<br>Date: ${new Date().toLocaleDateString('en-GB')}<br>${items.length} items</div>
</div>
<table>
  <thead><tr><th style="width:80px">Code</th><th>Description</th><th style="width:50px" class="center">Unit</th><th style="width:80px" class="num">Qty</th><th style="width:90px" class="num">Rate (${esc(currency)})</th><th style="width:100px" class="num">Amount (${esc(currency)})</th></tr></thead>
  <tbody>${tableRows}</tbody>
</table>
<table class="totals">
  <tr><td colspan="5" class="right" style="font-weight:600">Subtotal</td><td class="num" style="font-weight:600;width:100px">${fmt(Math.round(grandSubtotal * 100) / 100)}</td></tr>
  <tr><td colspan="5" class="right">VAT (${vatPct}%)</td><td class="num" style="width:100px">${fmt(Math.round(vatAmount * 100) / 100)}</td></tr>
  <tr class="grand"><td colspan="5" class="right">Grand Total</td><td class="num" style="width:100px">${fmt(Math.round(grandTotal * 100) / 100)}</td></tr>
</table>
<div class="footer"><span>Generated by ANGEL D.C.</span><span>Page 1</span></div>
<script>window.onload=()=>{window.print();}<\/script>
</body></html>`

  const win = window.open('', '_blank')
  if (win) {
    win.document.write(html)
    win.document.close()
  } else {
    throw new Error('Pop-up blocked. Please allow pop-ups for this site to export PDF.')
  }
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

function groupBySection(items: BOQItem[]): [string, BOQItem[]][] {
  const map = new Map<string, BOQItem[]>()
  for (const item of items) {
    const key = item.section ?? ''
    if (!map.has(key)) map.set(key, [])
    map.get(key)!.push(item)
  }
  return Array.from(map.entries())
}
