import type { MeasurementItem } from '@/lib/types'

export function exportMeasurementsToPDF(
  items: MeasurementItem[],
  projectName: string
) {
  const fmt = (n: number) => n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })

  let tableRows = ''
  let currentSection = ''

  for (const item of items) {
    if (item.section && item.section !== currentSection) {
      currentSection = item.section
      tableRows += `<tr class="section"><td colspan="9">${esc(currentSection.toUpperCase())}</td></tr>`
    }

    tableRows += `<tr class="item-header">
      <td>${esc(item.item_code ?? '')}</td>
      <td class="desc"><strong>${esc(item.description)}</strong></td>
      <td class="center">${esc(item.unit)}</td>
      <td></td><td></td><td></td><td></td><td></td>
      <td class="num total">${fmt(item.net_qty)}</td>
    </tr>`

    const lines = item.lines ?? []
    for (const line of lines) {
      tableRows += `<tr class="${line.is_deduction ? 'deduction' : ''}">
        <td></td>
        <td class="desc indent">${line.is_deduction ? '<span class="ded-badge">D</span> ' : ''}${esc(line.description ?? '')}</td>
        <td class="center">${esc(line.location ?? '')}</td>
        <td class="num">${line.nr ?? ''}</td>
        <td class="num">${line.length != null ? fmt(line.length) : ''}</td>
        <td class="num">${line.width != null ? fmt(line.width) : ''}</td>
        <td class="num">${line.height != null ? fmt(line.height) : ''}</td>
        <td class="formula">${esc(line.formula ?? '')}</td>
        <td class="num ${line.is_deduction ? 'neg' : ''}">${fmt(line.quantity)}</td>
      </tr>`
    }

    tableRows += `<tr class="item-total">
      <td colspan="8" class="right">Net: ${fmt(item.net_qty)} (Add: ${fmt(item.additions_qty)} | Ded: ${fmt(item.deductions_qty)})</td>
      <td class="num">${fmt(item.net_qty)}</td>
    </tr>`
  }

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Measurements - ${esc(projectName)}</title>
<style>
  @page { size: A4 landscape; margin: 12mm; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 9px; color: #1e293b; }
  .header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 14px; padding-bottom: 10px; border-bottom: 2px solid #1e40af; }
  .header h1 { font-size: 16px; color: #1e40af; }
  .header .meta { text-align: right; font-size: 8px; color: #64748b; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #1e40af; color: white; padding: 5px 6px; text-align: left; font-weight: 600; font-size: 8px; text-transform: uppercase; letter-spacing: 0.5px; }
  td { padding: 3px 6px; border-bottom: 1px solid #e2e8f0; font-size: 9px; }
  .section td { background: #f1f5f9; font-weight: 700; color: #334155; border-bottom: 1px solid #cbd5e1; padding: 6px; }
  .item-header td { background: #fafbfd; border-bottom: 1px solid #cbd5e1; }
  .item-total td { background: #f8fafc; font-weight: 600; font-size: 8px; color: #475569; border-bottom: 2px solid #cbd5e1; }
  .deduction td { color: #991b1b; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .right { text-align: right; }
  .center { text-align: center; }
  .desc { min-width: 180px; }
  .indent { padding-left: 20px !important; }
  .total { font-weight: 700; }
  .neg { color: #dc2626; }
  .formula { font-family: monospace; font-size: 8px; color: #64748b; }
  .ded-badge { background: #fecaca; color: #991b1b; padding: 0 3px; border-radius: 2px; font-size: 7px; font-weight: 700; }
  .footer { margin-top: 20px; padding-top: 6px; border-top: 1px solid #e2e8f0; font-size: 7px; color: #94a3b8; display: flex; justify-content: space-between; }
  @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
</style>
</head><body>
<div class="header">
  <div><h1>Measurement Book</h1><div style="font-size:11px;color:#475569;margin-top:2px">${esc(projectName)}</div></div>
  <div class="meta">Date: ${new Date().toLocaleDateString('en-GB')}<br>${items.length} items</div>
</div>
<table>
  <thead><tr>
    <th style="width:70px">Code</th><th>Description</th><th style="width:60px" class="center">Unit/Loc</th>
    <th style="width:40px" class="num">Nr</th><th style="width:60px" class="num">Length</th>
    <th style="width:60px" class="num">Width</th><th style="width:60px" class="num">Height</th>
    <th style="width:80px">Formula</th><th style="width:70px" class="num">Quantity</th>
  </tr></thead>
  <tbody>${tableRows}</tbody>
</table>
<div class="footer"><span>Generated by ANGEL D.C.</span><span>Page 1</span></div>
<script>window.onload=()=>{window.print();}<\/script>
</body></html>`

  const win = window.open('', '_blank')
  if (win) {
    win.document.write(html)
    win.document.close()
  } else {
    throw new Error('Pop-up blocked. Please allow pop-ups for this site to export PDF.')
  }
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}
