import type { Project, PaymentCert } from '@/lib/types'

export function exportPaymentReportToPDF(project: Project, certificates: PaymentCert[]) {
  const fmt = (n: number) => n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
  const currency = project.currency

  let tableRows = ''
  let totalGross = 0
  let totalRetention = 0
  let totalVAT = 0
  let totalNet = 0

  for (const cert of certificates) {
    totalGross += cert.gross_amount
    totalRetention += cert.retention_amount
    totalVAT += cert.vat_amount
    totalNet += cert.net_payable
    tableRows += `<tr>
      <td class="center">${cert.cert_number}</td>
      <td>${esc(cert.period_from)} - ${esc(cert.period_to)}</td>
      <td class="center">${esc(cert.status)}</td>
      <td class="num">${fmt(Math.round(cert.gross_amount * 100) / 100)}</td>
      <td class="num">${fmt(Math.round(cert.retention_amount * 100) / 100)}</td>
      <td class="num">${fmt(Math.round(cert.vat_amount * 100) / 100)}</td>
      <td class="num">${fmt(Math.round(cert.net_payable * 100) / 100)}</td>
    </tr>`
  }

  tableRows += `<tr class="subtotal">
    <td colspan="3" class="right">Total</td>
    <td class="num">${fmt(Math.round(totalGross * 100) / 100)}</td>
    <td class="num">${fmt(Math.round(totalRetention * 100) / 100)}</td>
    <td class="num">${fmt(Math.round(totalVAT * 100) / 100)}</td>
    <td class="num">${fmt(Math.round(totalNet * 100) / 100)}</td>
  </tr>`

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Payment Report - ${esc(project.name)}</title>
<style>
  @page { size: A4 landscape; margin: 15mm; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 10px; color: #1e293b; }
  .header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 16px; padding-bottom: 12px; border-bottom: 2px solid #1e40af; }
  .header h1 { font-size: 18px; color: #1e40af; }
  .header .meta { text-align: right; font-size: 9px; color: #64748b; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #1e40af; color: white; padding: 6px 8px; text-align: left; font-weight: 600; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
  td { padding: 5px 8px; border-bottom: 1px solid #e2e8f0; font-size: 10px; }
  tr:nth-child(even) { background: #f8fafc; }
  .section td { background: #f1f5f9; font-weight: 700; font-size: 10px; color: #334155; border-bottom: 1px solid #cbd5e1; padding: 8px; }
  .subtotal td { background: #f1f5f9; font-weight: 600; border-top: 1px solid #94a3b8; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .right { text-align: right; }
  .center { text-align: center; }
  .desc { min-width: 200px; }
  .totals { margin-top: 0; }
  .totals td { padding: 6px 8px; font-size: 10px; }
  .totals .grand { background: #1e40af; color: white; font-weight: 700; font-size: 12px; }
  .footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #e2e8f0; font-size: 8px; color: #94a3b8; display: flex; justify-content: space-between; }
  @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
</style>
</head><body>
<div class="header">
  <div><h1>Payment Report</h1><div style="font-size:12px;color:#475569;margin-top:2px">${esc(project.name)}</div></div>
  <div class="meta">Currency: ${esc(currency)}<br>Date: ${new Date().toLocaleDateString('en-GB')}<br>${certificates.length} certificates</div>
</div>
<table>
  <thead><tr><th style="width:60px" class="center">Cert #</th><th>Period</th><th style="width:80px" class="center">Status</th><th style="width:120px" class="num">Gross Amount (${esc(currency)})</th><th style="width:110px" class="num">Retention (${esc(currency)})</th><th style="width:100px" class="num">VAT (${esc(currency)})</th><th style="width:120px" class="num">Net Payable (${esc(currency)})</th></tr></thead>
  <tbody>${tableRows}</tbody>
</table>
<div class="footer"><span>Generated by ANGEL D.C.</span><span>Page 1</span></div>
<script>window.onload=()=>{window.print();}<\/script>
</body></html>`

  const win = window.open('', '_blank')
  if (win) {
    win.document.write(html)
    win.document.close()
  } else {
    throw new Error('Pop-up blocked. Please allow pop-ups for this site to export PDF.')
  }
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}
