import { createClient } from '@/lib/supabase/server'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { PrintButton } from '../fabrication-all/print-button'
import { ShapeCodeSVG } from '../[elementId]/shape-code-svg'

type Bar = {
  id: string
  bar_mark: string
  diameter_mm: number
  shape_code: string
  bending_dims: Record<string, number>
  cut_length_mm: number | null
  quantity: number
  unit_weight_kg_m: number | null
  total_weight_kg: number | null
  notes: string | null
}

type Element = {
  id: string
  element_mark: string
  element_type: string
  floor_level: string | null
  bars: Bar[]
}

export default async function BBSPackagePage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params
  const supabase = await createClient()

  const [{ data: project }, { data: rawElements }, { data: extractionPages }] = await Promise.all([
    supabase.from('projects').select('id, name, location, client_name, start_date, end_date').eq('id', id).single(),
    supabase
      .from('rebar_elements')
      .select('id, element_mark, element_type, floor_level, bars:rebar_bars(id, bar_mark, diameter_mm, shape_code, bending_dims, cut_length_mm, quantity, unit_weight_kg_m, total_weight_kg, notes, ocr_bbox)')
      .eq('project_id', id)
      .order('sort_order'),
    supabase
      .from('rebar_extraction_pages')
      .select('*')
      .eq('project_id', id)
      .order('page_number'),
  ])

  if (!project) notFound()
  const elements = (rawElements ?? []) as Element[]

  // Get signed URLs for extraction page images (for marked drawing in package)
  const markedDrawingPages = await Promise.all(
    (extractionPages ?? []).map(async (p: { image_storage_path: string; page_number: number }) => {
      const { data: signed } = await supabase.storage
        .from('drawings')
        .createSignedUrl(p.image_storage_path, 3600)
      return { page: p.page_number, url: signed?.signedUrl ?? null }
    })
  )

  const diaMap = new Map<number, { bars: number; lengthMm: number; weightKg: number }>()
  let grandTotal = 0
  let totalBars = 0
  for (const el of elements) {
    for (const bar of el.bars ?? []) {
      const d = bar.diameter_mm
      const row = diaMap.get(d) ?? { bars: 0, lengthMm: 0, weightKg: 0 }
      row.bars += bar.quantity
      row.lengthMm += (bar.cut_length_mm ?? 0) * bar.quantity
      row.weightKg += bar.total_weight_kg ?? 0
      diaMap.set(d, row)
      grandTotal += bar.total_weight_kg ?? 0
      totalBars += bar.quantity
    }
  }
  const diaRows = [...diaMap.entries()].sort((a, b) => a[0] - b[0])
  const today = new Date().toLocaleDateString('en-GB')

  return (
    <div className="min-h-screen bg-white text-gray-900 print:bg-white">
      {/* Screen header */}
      <div className="flex items-center gap-4 px-6 py-3 border-b border-gray-200 bg-slate-950 print:hidden">
        <Link href={`/projects/${id}/rebar`} className="text-slate-400 hover:text-slate-200 text-sm">
          ← Rebar Schedule
        </Link>
        <div className="w-px h-4 bg-slate-700" />
        <h1 className="text-base font-bold text-white">BBS Package — {project.name}</h1>
        <div className="ml-auto"><PrintButton /></div>
      </div>

      <div className="p-8 max-w-[210mm] mx-auto">

        {/* ═══════════════ COVER PAGE ═══════════════ */}
        <div className="min-h-[85vh] flex flex-col justify-center items-center text-center border-2 border-gray-400 p-12 mb-8 break-after-page">
          <p className="text-sm uppercase tracking-[0.3em] text-gray-500 mb-4">Bar Bending Schedule Package</p>
          <h1 className="text-4xl font-bold mb-2">{project.name}</h1>
          {project.location && <p className="text-lg text-gray-600 mb-6">{project.location}</p>}
          <div className="w-24 h-0.5 bg-amber-500 my-6" />
          <div className="grid grid-cols-2 gap-x-12 gap-y-3 text-sm text-left mt-4">
            {project.client_name && <><span className="text-gray-500">Client</span><span className="font-semibold">{project.client_name}</span></>}
            <span className="text-gray-500">Standard</span><span className="font-semibold">BS 8666:2020</span>
            <span className="text-gray-500">Steel Grade</span><span className="font-semibold">B500B</span>
            <span className="text-gray-500">Date</span><span className="font-semibold">{today}</span>
            <span className="text-gray-500">Elements</span><span className="font-semibold">{elements.length}</span>
            <span className="text-gray-500">Total Bars</span><span className="font-semibold">{totalBars}</span>
            <span className="text-gray-500">Total Weight</span><span className="font-semibold">{grandTotal.toFixed(2)} kg ({(grandTotal/1000).toFixed(3)} t)</span>
          </div>
          <p className="mt-12 text-xs text-gray-400">Generated by ANGEL D.C. Construction Management Platform</p>
        </div>

        {/* ═══════════════ PROJECT SUMMARY ═══════════════ */}
        <div className="mb-8 break-after-page">
          <h2 className="text-xl font-bold border-b-2 border-gray-400 pb-2 mb-6">Project Summary</h2>

          <div className="grid grid-cols-4 gap-4 mb-8">
            <SummaryCard label="Total Weight" value={`${grandTotal.toFixed(2)} kg`} sub={`${(grandTotal/1000).toFixed(3)} tonnes`} />
            <SummaryCard label="Total Bars" value={String(totalBars)} />
            <SummaryCard label="Elements" value={String(elements.length)} />
            <SummaryCard label="Diameters" value={String(diaRows.length)} sub={diaRows.map(([d]) => `T${d}`).join(', ')} />
          </div>

          {/* Weight by diameter table */}
          <h3 className="text-sm font-semibold uppercase tracking-wide text-gray-500 mb-2">Steel Summary by Diameter</h3>
          <table className="w-full text-sm border-collapse mb-6">
            <thead>
              <tr className="bg-gray-100">
                {['Diameter', 'Grade', 'Bars', 'Length (m)', 'Weight (kg)', 'Weight (t)', '% Total'].map(h => (
                  <th key={h} className="border border-gray-300 px-3 py-1.5 text-left font-semibold">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {diaRows.map(([d, row]) => (
                <tr key={d}>
                  <td className="border border-gray-300 px-3 py-1.5 font-mono font-bold">T{d}</td>
                  <td className="border border-gray-300 px-3 py-1.5">B500B</td>
                  <td className="border border-gray-300 px-3 py-1.5 text-right">{row.bars}</td>
                  <td className="border border-gray-300 px-3 py-1.5 text-right">{(row.lengthMm / 1000).toFixed(2)}</td>
                  <td className="border border-gray-300 px-3 py-1.5 text-right font-semibold">{row.weightKg.toFixed(2)}</td>
                  <td className="border border-gray-300 px-3 py-1.5 text-right">{(row.weightKg / 1000).toFixed(3)}</td>
                  <td className="border border-gray-300 px-3 py-1.5 text-right">{grandTotal > 0 ? ((row.weightKg / grandTotal) * 100).toFixed(1) : '0'}%</td>
                </tr>
              ))}
              <tr className="bg-gray-100 font-bold">
                <td colSpan={2} className="border border-gray-300 px-3 py-1.5">TOTAL</td>
                <td className="border border-gray-300 px-3 py-1.5 text-right">{diaRows.reduce((s, [, r]) => s + r.bars, 0)}</td>
                <td className="border border-gray-300 px-3 py-1.5 text-right">{(diaRows.reduce((s, [, r]) => s + r.lengthMm, 0) / 1000).toFixed(2)}</td>
                <td className="border border-gray-300 px-3 py-1.5 text-right">{grandTotal.toFixed(2)}</td>
                <td className="border border-gray-300 px-3 py-1.5 text-right">{(grandTotal / 1000).toFixed(3)}</td>
                <td className="border border-gray-300 px-3 py-1.5 text-right">100%</td>
              </tr>
            </tbody>
          </table>

          {/* Weight by element */}
          <h3 className="text-sm font-semibold uppercase tracking-wide text-gray-500 mb-2">Weight by Element</h3>
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="bg-gray-100">
                {['Element', 'Type', 'Level', 'Bars', 'Weight (kg)', '% Total'].map(h => (
                  <th key={h} className="border border-gray-300 px-3 py-1.5 text-left font-semibold">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {elements.map(el => {
                const elW = (el.bars ?? []).reduce((s, b) => s + (b.total_weight_kg ?? 0), 0)
                const elBars = (el.bars ?? []).reduce((s, b) => s + b.quantity, 0)
                return (
                  <tr key={el.id}>
                    <td className="border border-gray-300 px-3 py-1.5 font-bold">{el.element_mark}</td>
                    <td className="border border-gray-300 px-3 py-1.5">{el.element_type}</td>
                    <td className="border border-gray-300 px-3 py-1.5">{el.floor_level ?? '—'}</td>
                    <td className="border border-gray-300 px-3 py-1.5 text-right">{elBars}</td>
                    <td className="border border-gray-300 px-3 py-1.5 text-right font-semibold">{elW.toFixed(2)}</td>
                    <td className="border border-gray-300 px-3 py-1.5 text-right">{grandTotal > 0 ? ((elW / grandTotal) * 100).toFixed(1) : '0'}%</td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>

        {/* ═══════════════ PER-ELEMENT BBS + FABRICATION ═══════════════ */}
        {elements.map(el => {
          const elTotal = (el.bars ?? []).reduce((s, b) => s + (b.total_weight_kg ?? 0), 0)
          return (
            <div key={el.id} className="mb-10 break-inside-avoid-page">
              <div className="flex items-center gap-4 mb-3 pb-2 border-b-2 border-gray-400">
                <span className="text-xs uppercase tracking-wide text-gray-500">{el.element_type}</span>
                <span className="text-2xl font-bold">{el.element_mark}</span>
                {el.floor_level && <span className="text-gray-500 text-sm">{el.floor_level}</span>}
                <span className="ml-auto text-sm font-semibold">{elTotal.toFixed(3)} kg</span>
              </div>

              {/* Fabrication drawings */}
              <div className="grid grid-cols-2 gap-3 mb-4">
                {(el.bars ?? []).map(bar => (
                  <div key={bar.id} className="border border-gray-300 rounded p-3">
                    <div className="flex items-center justify-between mb-1">
                      <span className="font-mono font-bold text-lg">Bar {bar.bar_mark}</span>
                      <span className="text-sm text-gray-500">T{bar.diameter_mm} · SC {bar.shape_code}</span>
                    </div>
                    <ShapeCodeSVG shapeCode={bar.shape_code} dims={bar.bending_dims ?? {}} showDims />
                    <div className="mt-1 flex gap-4 text-xs text-gray-500">
                      <span>Qty: <strong className="text-gray-800">{bar.quantity}</strong></span>
                      {bar.cut_length_mm && <span>Cut L: <strong className="text-gray-800">{bar.cut_length_mm.toFixed(0)} mm</strong></span>}
                      {bar.total_weight_kg && <span>Wt: <strong className="text-gray-800">{bar.total_weight_kg.toFixed(3)} kg</strong></span>}
                    </div>
                  </div>
                ))}
              </div>

              {/* BBS table */}
              <table className="w-full text-xs border-collapse">
                <thead>
                  <tr className="bg-gray-100">
                    {['Mark', 'T', 'Shape', 'A', 'B', 'C', 'D', 'Qty', 'Cut L (mm)', 'Wt (kg)', 'Notes'].map(h => (
                      <th key={h} className="border border-gray-300 px-2 py-1.5 text-left font-semibold">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {(el.bars ?? []).map(bar => (
                    <tr key={bar.id}>
                      <td className="border border-gray-300 px-2 py-1 font-mono font-bold">{bar.bar_mark}</td>
                      <td className="border border-gray-300 px-2 py-1">T{bar.diameter_mm}</td>
                      <td className="border border-gray-300 px-2 py-1">{bar.shape_code}</td>
                      <td className="border border-gray-300 px-2 py-1 text-right">{bar.bending_dims?.A ?? '—'}</td>
                      <td className="border border-gray-300 px-2 py-1 text-right">{bar.bending_dims?.B ?? '—'}</td>
                      <td className="border border-gray-300 px-2 py-1 text-right">{bar.bending_dims?.C ?? '—'}</td>
                      <td className="border border-gray-300 px-2 py-1 text-right">{bar.bending_dims?.D ?? '—'}</td>
                      <td className="border border-gray-300 px-2 py-1 text-right">{bar.quantity}</td>
                      <td className="border border-gray-300 px-2 py-1 text-right font-mono">{bar.cut_length_mm?.toFixed(0) ?? '—'}</td>
                      <td className="border border-gray-300 px-2 py-1 text-right font-semibold">{bar.total_weight_kg?.toFixed(3) ?? '—'}</td>
                      <td className="border border-gray-300 px-2 py-1 text-gray-500 max-w-[120px] truncate">{bar.notes ?? ''}</td>
                    </tr>
                  ))}
                  <tr className="bg-gray-50 font-bold">
                    <td colSpan={9} className="border border-gray-300 px-2 py-1.5 text-right text-gray-500">Element total</td>
                    <td className="border border-gray-300 px-2 py-1.5 text-right">{elTotal.toFixed(3)}</td>
                    <td className="border border-gray-300" />
                  </tr>
                </tbody>
              </table>
            </div>
          )
        })}

        {/* ═══════════════ MARKED DRAWING ═══════════════ */}
        {markedDrawingPages.filter(p => p.url).length > 0 && (
          <div className="mt-8 break-before-page">
            <h2 className="text-lg font-bold border-b-2 border-gray-400 pb-2 mb-4">Marked Drawing</h2>
            {markedDrawingPages.filter(p => p.url).map(p => (
              <div key={p.page} className="mb-6 break-inside-avoid">
                {markedDrawingPages.length > 1 && (
                  <p className="text-sm text-gray-500 mb-2">Page {p.page}</p>
                )}
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={p.url!} alt={`Extraction page ${p.page}`} className="w-full border border-gray-300 rounded" />
              </div>
            ))}
            <p className="text-xs text-gray-500 mt-2">Source drawing with detected rebar callout positions from OCR extraction.</p>
          </div>
        )}

        {/* ═══════════════ DRAWING REFERENCES ═══════════════ */}
        <div className="mt-8 break-before-page">
          <h2 className="text-lg font-bold border-b-2 border-gray-400 pb-2 mb-4">Drawing References</h2>
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="bg-gray-100">
                {['Element', 'Type', 'Level', 'Bar Marks', 'Diameters Used'].map(h => (
                  <th key={h} className="border border-gray-300 px-3 py-1.5 text-left font-semibold">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {elements.map(el => {
                const marks = (el.bars ?? []).map(b => b.bar_mark).join(', ')
                const dias = [...new Set((el.bars ?? []).map(b => b.diameter_mm))].sort((a, b) => a - b).map(d => `T${d}`).join(', ')
                return (
                  <tr key={el.id}>
                    <td className="border border-gray-300 px-3 py-1.5 font-bold">{el.element_mark}</td>
                    <td className="border border-gray-300 px-3 py-1.5">{el.element_type}</td>
                    <td className="border border-gray-300 px-3 py-1.5">{el.floor_level ?? '—'}</td>
                    <td className="border border-gray-300 px-3 py-1.5 font-mono text-xs">{marks || '—'}</td>
                    <td className="border border-gray-300 px-3 py-1.5">{dias || '—'}</td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>

        <div className="mt-8 text-xs text-gray-400 text-center">
          Generated by ANGEL D.C. Construction Management · BS 8666:2020 · {today}
        </div>
      </div>

      <style>{`
        @media print {
          @page { size: A4 portrait; margin: 12mm; }
          .print\\:hidden { display: none !important; }
          body { background: white !important; color: black !important; font-size: 9pt; }
          h1, h2, h3 { break-after: avoid; }
          table { page-break-inside: auto; }
          tr { page-break-inside: avoid; }
          thead { display: table-header-group; }
          .break-after-page { break-after: page; }
          .break-before-page { break-before: page; }
        }
      `}</style>
    </div>
  )
}

function SummaryCard({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div className="border border-gray-300 rounded-lg p-4 text-center">
      <p className="text-xs uppercase tracking-wide text-gray-500 mb-1">{label}</p>
      <p className="text-2xl font-bold">{value}</p>
      {sub && <p className="text-xs text-gray-500 mt-1">{sub}</p>}
    </div>
  )
}
